version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: meetdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    networks:
      - meet-network
    volumes:
      - meet-mysql-data:/var/lib/mysql

  minio:
    image: docker.io/bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKET: defaultbucket
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - meet-network
    volumes:
      - meet-minio-data:/data

networks:
  meet-network:
    driver: bridge

volumes:
  meet-mysql-data:
  meet-minio-data:

